Fix handling empty tags from replies
go-graphite/carbonapi pull request #566
Opened 2021-02-17 17:30 UTC by Civil

As backends might reply with an empty tag or with a tag without value, carbonapi
should skip such broken tags.

Fixes #565

2021-02-18 11:50 UTC, Hipska requested changes
Seems there is still a minor problem if that empty tag is at the end of the string: https://play.golang.org/p/W4dXsUjj5yb

2021-02-18 19:02 UTC, Civil commented
I've changed the code and added a bit more tests, now it should work fine.

2021-02-18 21:08 UTC, Hipska approved these changes
My small test indeed seems ok now 👍

2021-02-20 12:01 UTC, deniszh approved these changes

2021-02-20 12:14 UTC, merged