Add support for Graphite web exp() function (#2)
go-graphite/carbonapi pull request #685
Opened 2022-09-01 22:36 UTC by carrieedwards

This PR adds support for the Graphite web exp() function, which is defined in the [Graphite web docs](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.exp)

```
exp(seriesList)
Raise e to the power of the datapoint, where e = 2.718281… is the base of natural logarithms.

Example:

&target=exp(Server.instance01.threads.busy)

```

 It also adds a test to verify the function works as expected.

2022-09-02 03:55 UTC, msaf1980 commented on expr/functions/exp/function.go
> +		r := *a
May be rewrite like https://github.com/go-graphite/carbonapi/blob/main/expr/functions/ewma/function.go#L50 ?
For avoid alloc-copy during unreference/reference and fmt.Snprintf ?

2022-09-03 21:35 UTC, Civil requested changes

2022-09-03 21:35 UTC, Civil commented on expr/functions/exp/function_test.go
> +	"github.com/grafana/carbonapi/expr/helper"
I think you forgot to replace imports in the tests

2022-09-06 20:21 UTC, carrieedwards commented
I am going to close this PR as we will be sending a PR with nearly all of our changes  made in the Grafana fork in the coming days.

2022-09-06 20:21 UTC, closed without merging